#!/bin/bash

nomCapteur=$1
#On récupère les 7derniers fichiers pour un capteur (logiquement trier par ordre alphabétique donc par date)
cd SENSOR/$nomCapteur
listeFichier=$(ls)
echo $listeFichier > listeFichierMesureTmp
awk '{print $7}' listeFichierMesureTmp > tmp
fichierJ7=$(cat tmp)
awk '{print $6}' listeFichierMesureTmp > tmp
fichierJ6=$(cat tmp)
awk '{print $5}' listeFichierMesureTmp > tmp
fichierJ5=$(cat tmp)
awk '{print $4}' listeFichierMesureTmp > tmp
fichierJ4=$(cat tmp)
awk '{print $3}' listeFichierMesureTmp > tmp
fichierJ3=$(cat tmp)
awk '{print $2}' listeFichierMesureTmp > tmp
fichierJ2=$(cat tmp)
awk '{print $1}' listeFichierMesureTmp > tmp
fichierJ1=$(cat tmp)

typeDeMesure=$(awk '{print $12}' $nomCapteur.attrib)
unite=$(awk '{print $15}' $nomCapteur.attrib)
nomYFinal=$typeDeMesure" "en" "$unite
dateJ1=$(awk '{print $1}' listeFichierMesureTmp)

rm listeFichierMesureTmp
rm tmp

cd ../../STAT
mkdir $nomCapteur
cd $nomCapteur

cat ../../SENSOR/$nomCapteur/$fichierJ1 >> mesureHebdo
cat ../../SENSOR/$nomCapteur/$fichierJ2 >> mesureHebdo
cat ../../SENSOR/$nomCapteur/$fichierJ3 >> mesureHebdo
cat ../../SENSOR/$nomCapteur/$fichierJ4 >> mesureHebdo
cat ../../SENSOR/$nomCapteur/$fichierJ5 >> mesureHebdo
cat ../../SENSOR/$nomCapteur/$fichierJ6 >> mesureHebdo
cat ../../SENSOR/$nomCapteur/$fichierJ7 >> mesureHebdo

#On dessine
#On récupérer le min et le max de notre suite de nombre
min=100000
max=0
mesures=$(cat mesureHebdo)
for mesure in $mesures
do
	if [ "$mesure" -le "$min" ]; then
		min=$mesure
	fi
	if [ "$mesure" -ge "$max" ]; then
		max=$mesure
	fi
done


xmin=0
wc -l mesureHebdo > tmpNbLigne
xmax=$(awk '{print $1}' tmpNbLigne)
rm tmpNbLigne
ymin=$min
ymax=$max

echo "set terminal png size 800,500 enhanced background rgb 'white'" >> gnuplot_script
echo "set style line 1 lt 1 lw 1.5 pt 3 linecolor rgb '#2b63ff'" >> gnuplot_script
echo "set output '$dateJ1.png'" >> gnuplot_script
echo "set xtic auto" >> gnuplot_script
echo "set ytic auto" >> gnuplot_script
echo "set title '$dateJ1'" >> gnuplot_script
echo "set ylabel '$nomYFinal'" >> gnuplot_script
echo "set xlabel 'Jour'" >> gnuplot_script
echo "set xr [$xmin:$xmax]" >> gnuplot_script
echo "set yr [$ymin:$ymax]" >> gnuplot_script
echo "set nokey" >> gnuplot_script
echo "plot 'mesureHebdo' with linespoints ls 1" >> gnuplot_script

gnuplot gnuplot_script

#On supprime les files temporaires
rm gnuplot_script
rm mesureHebdo





