#!/bin/bash

capteur=$1

cd ../SENSOR/$capteur
listeFileMesure=$(ls)

for mesure in $listeFileMesure
do
	if [ "$mesure" != "$capteur.attrib" ]; then
		#On récupère toute les mesures dans un fichier
		cat $mesure >> totalMesure	
	fi
done

totalMesure=$(cat totalMesure)
max=0

for mesure in $totalMesure
do
	if [ "$mesure" -ge "$max" ]; then
		max=$mesure
	fi
done

echo "La mesure maximale pour ce capteur est : "$max
rm totalMesure
